version: '3'
services:

  opc-postgres:
    image: postgres
    restart: "always"
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    ports:
      - 5001:5432
    environment:
      - POSTGRES_DB=OPC_DATA
      - POSTGRES_USER=OPC_CLIENT
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
