CREATE TABLE IF NOT EXISTS actuator_position (
  id SERIAL PRIMARY KEY,
  value INT NOT NULL,
  ts TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ekstruder_value (
  id SERIAL PRIMARY KEY,
  value INT NOT NULL,
  ts TIMESTAMP
);

CREATE TABLE IF NOT EXISTS level_sensor (
  id SERIAL PRIMARY KEY,
  value BOOLEAN NOT NULL,
  ts TIMESTAMP
);

CREATE TABLE IF NOT EXISTS piston_rop (
  id SERIAL PRIMARY KEY,
  value BOOLEAN NOT NULL,
  ts TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pump_pressure (
  id SERIAL PRIMARY KEY,
  value INT NOT NULL,
  ts TIMESTAMP
);

CREATE TABLE IF NOT EXISTS temperature_sensor (
  id SERIAL PRIMARY KEY,
  value FLOAT NOT NULL,
  ts TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vector_data (
  id SERIAL PRIMARY KEY,
  value1 FLOAT NOT NULL,
  value2 FLOAT NOT NULL,
  value3 FLOAT NOT NULL,
  ts TIMESTAMP
);

CREATE TABLE IF NOT EXISTS work_time (
  id SERIAL PRIMARY KEY,
  value FLOAT NOT NULL,
  ts TIMESTAMP
);